language: node_js
node_js:
    - stable
branches:
    only:
        - master
        - develop
script:
    - npm install
    - npm run build
notifications:
    email:
        on_success: never
        on_failure: always
deploy:
    provider: heroku
    api_key:
        secure: Qp89mPTdnrxz9IPDNRqoIGV0BfMf9hkb67cL0ITMdQVwXpMJlamEyKKYNN05oG4/vMxMHV6Nr3wgfb4oT1EVFvWC5kwFYjGzEQP+4hY7LsOBKtbf+thFO9ap2+MKeuzm40evF8q5/XyW0MjPyfETKvCEdv19DXSD5GGUyv5EQXnzQPb2+1J4oZYZcGDO3mIcxHR0SXQfzh68Py0OGKAieihOrbvvEBhj6/M8kUA6uExXIHQewHW0BPF4xhUlInr8Xv2N6ckV0XSRtfiCtBQVke1GXOrC4RD9nuD9YTVg44cLVq9ANE0d/kERJJ5nBUNoVBRue8xXltqQ0kUWJAGS3+expHAS+xmoayyJcnRUuIgFI/SkhySeP2Vksc/eT6lxQ8apS0cXBQvEMa7sNOE9QMCX0HyTOMZ7K6Ytw4ciPdLhhZWg5wCXN9J9k5gGgCF89CxSP+UJz178WOqxmNDVt7SxF+DfeNlOp5XN8mp8FcFME/qWUbMTpCmD78N+Eo+2k8CxRsg/fbfmW6GPDJgfABDJ/HCdNWMxTHsmwpRdPEGav2d1MHt6bqo1GSFJsVPHy96JoRYDqeE6VP0BzeNIxSS5OchC57UwpRH15h0kimy8dquEVxD4RWR65mFr899ov+FM0VRQspTOiO/UL9u5iO4LfAVJ/ddaGsjhRTSZ1lM=
    app: imuaythai
deploy:
    provider: heroku
    api_key:
        secure: Qp89mPTdnrxz9IPDNRqoIGV0BfMf9hkb67cL0ITMdQVwXpMJlamEyKKYNN05oG4/vMxMHV6Nr3wgfb4oT1EVFvWC5kwFYjGzEQP+4hY7LsOBKtbf+thFO9ap2+MKeuzm40evF8q5/XyW0MjPyfETKvCEdv19DXSD5GGUyv5EQXnzQPb2+1J4oZYZcGDO3mIcxHR0SXQfzh68Py0OGKAieihOrbvvEBhj6/M8kUA6uExXIHQewHW0BPF4xhUlInr8Xv2N6ckV0XSRtfiCtBQVke1GXOrC4RD9nuD9YTVg44cLVq9ANE0d/kERJJ5nBUNoVBRue8xXltqQ0kUWJAGS3+expHAS+xmoayyJcnRUuIgFI/SkhySeP2Vksc/eT6lxQ8apS0cXBQvEMa7sNOE9QMCX0HyTOMZ7K6Ytw4ciPdLhhZWg5wCXN9J9k5gGgCF89CxSP+UJz178WOqxmNDVt7SxF+DfeNlOp5XN8mp8FcFME/qWUbMTpCmD78N+Eo+2k8CxRsg/fbfmW6GPDJgfABDJ/HCdNWMxTHsmwpRdPEGav2d1MHt6bqo1GSFJsVPHy96JoRYDqeE6VP0BzeNIxSS5OchC57UwpRH15h0kimy8dquEVxD4RWR65mFr899ov+FM0VRQspTOiO/UL9u5iO4LfAVJ/ddaGsjhRTSZ1lM=
    app: imuaythai-dev
