version: 3
services:
  api:
        build: ./api
        ports:
            - "8000:80"
        depends_on:
            - db
            -front
    db:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "your_password"
            ACCEPT_EULA: "Y"
    front:
    build: ./client