export const FETCH_CONTEST_EVENTS = 'FETCH_CONTEST_EVENTS';
export const FETCH_CONTEST_EVENTS_FULFILLED = 'FETCH_CONTEST_EVENTS_FULFILLED';
export const FETCH_CONTEST_EVENTS_REJECTED = 'FETCH_CONTEST_EVENTS_REJECTED';
