export const FETCH_LICENSE_TYPES = "FETCH_LICENSE_TYPES";
export const FETCH_LICENSE_TYPES_FULFILLED = "FETCH_LICENSE_TYPES_FULFILLED";
export const FETCH_LICENSE_TYPES_REJECTED = "FETCH_LICENSE_TYPES_REJECTED";

export const FETCH_PAYMENT = "FETCH_PAYMENT";
export const FETCH_PAYMENT_FULFILLED = "FETCH_PAYMENT_FULFILLED";
export const FETCH_PAYMENT_REJECTED = "FETCH_PAYMENT_REJECTED";

export const FETCH_LICENSE_CURRENT_CONTESTS = "FETCH_LICENSE_CURRENT_CONTESTS";
export const FETCH_LICENSE_CURRENT_CONTESTS_FULFILLED = "FETCH_LICENSE_CURRENT_CONTESTS_FULFILLED";
export const FETCH_LICENSE_CURRENT_CONTESTS_REJECTED = "FETCH_LICENSE_CURRENT_CONTESTS_REJECTED";


